apiVersion: apps/v1
kind: Deployment
metadata:
  name: kine
  namespace: tekton-apiserver
spec:
  template:
    spec:
      containers:
      - name: kine
        args:
        - --endpoint=postgres://kine:kine-poc-secret@postgresql.tekton-apiserver.svc:5432/kine?sslmode=disable
        - --listen-address=tcp://0.0.0.0:2379
