apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../phase3
- postgresql.yaml

images:
- name: registry.access.redhat.com/hi/postgresql
  newName: registry.access.redhat.com/hi/postgresql
  newTag: "18.4"

patches:
- target:
    kind: Deployment
    name: kine
  path: kine-patch.yaml
