//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIGroupSpec) DeepCopyInto(out *APIGroupSpec) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGroupSpec.
func (in *APIGroupSpec) DeepCopy() *APIGroupSpec {
	if in == nil {
		return nil
	}
	out := new(APIGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShard) DeepCopyInto(out *APIShard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShard.
func (in *APIShard) DeepCopy() *APIShard {
	if in == nil {
		return nil
	}
	out := new(APIShard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShardList) DeepCopyInto(out *APIShardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIShard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShardList.
func (in *APIShardList) DeepCopy() *APIShardList {
	if in == nil {
		return nil
	}
	out := new(APIShardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIShardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShardSpec) DeepCopyInto(out *APIShardSpec) {
	*out = *in
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]APIGroupSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.NamespaceSync.DeepCopyInto(&out.NamespaceSync)
	in.Secondary.DeepCopyInto(&out.Secondary)
	in.Kine.DeepCopyInto(&out.Kine)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShardSpec.
func (in *APIShardSpec) DeepCopy() *APIShardSpec {
	if in == nil {
		return nil
	}
	out := new(APIShardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIShardStatus) DeepCopyInto(out *APIShardStatus) {
	*out = *in
	if in.ConnectionSecret != nil {
		in, out := &in.ConnectionSecret, &out.ConnectionSecret
		*out = new(ConnectionSecretReference)
		**out = **in
	}
	if in.RegisteredAPIServices != nil {
		in, out := &in.RegisteredAPIServices, &out.RegisteredAPIServices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIShardStatus.
func (in *APIShardStatus) DeepCopy() *APIShardStatus {
	if in == nil {
		return nil
	}
	out := new(APIShardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompactionConfig) DeepCopyInto(out *CompactionConfig) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MinRetain != nil {
		in, out := &in.MinRetain, &out.MinRetain
		*out = new(int64)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompactionConfig.
func (in *CompactionConfig) DeepCopy() *CompactionConfig {
	if in == nil {
		return nil
	}
	out := new(CompactionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPoolConfig) DeepCopyInto(out *ConnectionPoolConfig) {
	*out = *in
	if in.MaxIdleConnections != nil {
		in, out := &in.MaxIdleConnections, &out.MaxIdleConnections
		*out = new(int32)
		**out = **in
	}
	if in.MaxOpenConnections != nil {
		in, out := &in.MaxOpenConnections, &out.MaxOpenConnections
		*out = new(int32)
		**out = **in
	}
	if in.MaxLifetime != nil {
		in, out := &in.MaxLifetime, &out.MaxLifetime
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPoolConfig.
func (in *ConnectionPoolConfig) DeepCopy() *ConnectionPoolConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectionPoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSecretReference) DeepCopyInto(out *ConnectionSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSecretReference.
func (in *ConnectionSecretReference) DeepCopy() *ConnectionSecretReference {
	if in == nil {
		return nil
	}
	out := new(ConnectionSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InClusterStorage) DeepCopyInto(out *InClusterStorage) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InClusterStorage.
func (in *InClusterStorage) DeepCopy() *InClusterStorage {
	if in == nil {
		return nil
	}
	out := new(InClusterStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KineSpec) DeepCopyInto(out *KineSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ConnectionPool != nil {
		in, out := &in.ConnectionPool, &out.ConnectionPool
		*out = new(ConnectionPoolConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Compaction != nil {
		in, out := &in.Compaction, &out.Compaction
		*out = new(CompactionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PollBatchSize != nil {
		in, out := &in.PollBatchSize, &out.PollBatchSize
		*out = new(int64)
		**out = **in
	}
	if in.WatchProgressNotifyInterval != nil {
		in, out := &in.WatchProgressNotifyInterval, &out.WatchProgressNotifyInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KineSpec.
func (in *KineSpec) DeepCopy() *KineSpec {
	if in == nil {
		return nil
	}
	out := new(KineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretReference.
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSync) DeepCopyInto(out *NamespaceSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSync.
func (in *NamespaceSync) DeepCopy() *NamespaceSync {
	if in == nil {
		return nil
	}
	out := new(NamespaceSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSyncConfig) DeepCopyInto(out *NamespaceSyncConfig) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSyncConfig.
func (in *NamespaceSyncConfig) DeepCopy() *NamespaceSyncConfig {
	if in == nil {
		return nil
	}
	out := new(NamespaceSyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSyncList) DeepCopyInto(out *NamespaceSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamespaceSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSyncList.
func (in *NamespaceSyncList) DeepCopy() *NamespaceSyncList {
	if in == nil {
		return nil
	}
	out := new(NamespaceSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSyncSpec) DeepCopyInto(out *NamespaceSyncSpec) {
	*out = *in
	out.SecondaryConnection = in.SecondaryConnection
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSyncSpec.
func (in *NamespaceSyncSpec) DeepCopy() *NamespaceSyncSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSyncStatus) DeepCopyInto(out *NamespaceSyncStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSyncStatus.
func (in *NamespaceSyncStatus) DeepCopy() *NamespaceSyncStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryConnectionSpec) DeepCopyInto(out *SecondaryConnectionSpec) {
	*out = *in
	out.ServiceRef = in.ServiceRef
	out.AuthSecretRef = in.AuthSecretRef
	out.CASecretRef = in.CASecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryConnectionSpec.
func (in *SecondaryConnectionSpec) DeepCopy() *SecondaryConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(SecondaryConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondarySpec) DeepCopyInto(out *SecondarySpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondarySpec.
func (in *SecondarySpec) DeepCopy() *SecondarySpec {
	if in == nil {
		return nil
	}
	out := new(SecondarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceReference) DeepCopyInto(out *ServiceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceReference.
func (in *ServiceReference) DeepCopy() *ServiceReference {
	if in == nil {
		return nil
	}
	out := new(ServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.ConnectionSecretRef != nil {
		in, out := &in.ConnectionSecretRef, &out.ConnectionSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.InCluster != nil {
		in, out := &in.InCluster, &out.InCluster
		*out = new(InClusterStorage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncedWebhookCounts) DeepCopyInto(out *SyncedWebhookCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncedWebhookCounts.
func (in *SyncedWebhookCounts) DeepCopy() *SyncedWebhookCounts {
	if in == nil {
		return nil
	}
	out := new(SyncedWebhookCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSync) DeepCopyInto(out *WebhookSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSync.
func (in *WebhookSync) DeepCopy() *WebhookSync {
	if in == nil {
		return nil
	}
	out := new(WebhookSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSyncList) DeepCopyInto(out *WebhookSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebhookSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSyncList.
func (in *WebhookSyncList) DeepCopy() *WebhookSyncList {
	if in == nil {
		return nil
	}
	out := new(WebhookSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSyncSpec) DeepCopyInto(out *WebhookSyncSpec) {
	*out = *in
	out.SecondaryConnection = in.SecondaryConnection
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSyncSpec.
func (in *WebhookSyncSpec) DeepCopy() *WebhookSyncSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSyncStatus) DeepCopyInto(out *WebhookSyncStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.SyncedWebhooks = in.SyncedWebhooks
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSyncStatus.
func (in *WebhookSyncStatus) DeepCopy() *WebhookSyncStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookSyncStatus)
	in.DeepCopyInto(out)
	return out
}
