apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.tekton.dev
spec:
  group: tekton.dev
  version: v1
  service:
    namespace: tekton-apiserver
    name: tekton-apiserver
  caBundle: PLACEHOLDER
  groupPriorityMinimum: 1000
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.tekton.dev
spec:
  group: tekton.dev
  version: v1beta1
  service:
    namespace: tekton-apiserver
    name: tekton-apiserver
  caBundle: PLACEHOLDER
  groupPriorityMinimum: 1000
  versionPriority: 50
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.resolution.tekton.dev
spec:
  group: resolution.tekton.dev
  version: v1beta1
  service:
    namespace: tekton-apiserver
    name: tekton-apiserver
  caBundle: PLACEHOLDER
  groupPriorityMinimum: 1000
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.resolution.tekton.dev
spec:
  group: resolution.tekton.dev
  version: v1alpha1
  service:
    namespace: tekton-apiserver
    name: tekton-apiserver
  caBundle: PLACEHOLDER
  groupPriorityMinimum: 1000
  versionPriority: 50
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.tekton.dev
spec:
  group: tekton.dev
  version: v1alpha1
  service:
    namespace: tekton-apiserver
    name: tekton-apiserver
  caBundle: PLACEHOLDER
  groupPriorityMinimum: 1000
  versionPriority: 10
